nelmio_cors:
    defaults:
        origin_regex: false
        # Añadimos los orígenes de Expo (Web y Local)
        allow_origin: ["http://localhost:5173", "http://localhost:8081", "*"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/api/":
            origin_regex: false
            # Usar '*' en desarrollo es lo más sano para no pelear con IPs dinámicas
            allow_origin: ["*"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            allow_headers: ["*"]
            max_age: 3600